services:
  node:
    build: .
    restart: always
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: mongodb://mongo:27018/
    links:
      - mongo
  mongo:
    image: mongo
    user: "${UID}:${UID}"
    restart: always
    command: mongod --port 27018
    volumes:
      - ./data/mongodb:/data/db
